from django.contrib import admin
from django.urls import path
from myapp import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('user_dashboard/', views.user_dashboard, name='user_dashboard'),
    path('index/', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('addnew', views.addnew, name='addnew'),
    path('update/<int:id>', views.update, name='update'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete_employee, name='delete'),
    path('out/', views.out, name='out'),
    path('sidebar/', views.sidebar, name='sidebar'),
    path('addvisitor/', views.add_visitor, name='add_visitor'),
    path('editvisitor/<int:visitor_id>/', views.edit_visitor, name='edit_visitor'),
    path('deletevisitor/<int:visitor_id>/', views.delete_visitor, name='delete_visitor'),
    path('updatevisitor/<int:visitor_id>/', views.update_visitor, name='update_visitor'),
    path('logout/', views.logout_view, name='logout'),
    path('visites/', views.gestion_visites, name='gestion_visites'),
    path('visites/create/', views.VisiteCreateView.as_view(), name='visite_create'),
    path('visites/<int:pk>/update/', views.VisiteUpdateView.as_view(), name='visite_update'),
    path('visites/<int:pk>/delete/', views.VisiteDeleteView.as_view(), name='visite_delete'),
    path('visites/historique/', views.historique_visites, name='historique_visites'),
    path('visites/en-cours/', views.visites_en_cours, name='visites_en_cours'),
    path('visites/terminer/<int:pk>/', views.terminer_visite, name='terminer_visite'),
    path('visites/create/<int:visitor_id>/<int:employee_id>/', views.create_visite, name='create_visite_with_data'),
    path('courriers/', views.list_courriers, name='list_courriers'),
    path('courriers/add/', views.add_courrier, name='add_courrier'),
    path('courriers/edit/<int:pk>/', views.edit_courrier, name='edit_courrier'),
    path('courriers/delete/<int:pk>/', views.delete_courrier, name='delete_courrier'),
    path('gestion-courriers/', views.gestion_courriers, name='gestion_courriers'),
    path('courriers/', views.courriers, name='courriers'),
    path('courriers_en_cours/', views.courriers_en_cours, name='courriers_en_cours'),
    path('terminer_courrier/<int:pk>/', views.terminer_courrier, name='terminer_courrier'),
    path('bi_user/', views.bi_user, name='bi_user'),    
    path('bi_admin/', views.bi_admin, name='bi_admin'),
    path('', views.login_view, name='root'),
]
